name: Fetch GW Data Python
on:
  schedule:
    - cron: 0 20 * * 0
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify the version of Python you want to use
          cache: 'pip' # Enable pip cache

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the Python script
        run: python fetch-gw-data.py

        # Move or ensure output is in the 'data/' folder
      - name: Move output to data folder
        run: |
          mkdir -p data
          mv Gameweek*.json data/ || true

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git diff --cached --quiet || git commit -m "Weekly data fetch"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's token to authenticate push
